/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface MockCycleFactoryInterface extends Interface {
  getFunction(nameOrSignature: "getAllCycles" | "setCycles"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getAllCycles",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setCycles",
    values: [AddressLike[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "getAllCycles",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setCycles", data: BytesLike): Result;
}

export interface MockCycleFactory extends BaseContract {
  connect(runner?: ContractRunner | null): MockCycleFactory;
  waitForDeployment(): Promise<this>;

  interface: MockCycleFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getAllCycles: TypedContractMethod<[], [string[]], "view">;

  setCycles: TypedContractMethod<
    [_cycles: AddressLike[]],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getAllCycles"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "setCycles"
  ): TypedContractMethod<[_cycles: AddressLike[]], [void], "nonpayable">;

  filters: {};
}
