/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface OperatorRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "operators"
      | "recordCompletion"
      | "recordCycle"
      | "recordDefault"
      | "registerOperator"
      | "reputationScore"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CycleCompleted"
      | "CycleDefaulted"
      | "CycleRecorded"
      | "OperatorRegistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "operators",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recordCompletion",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recordCycle",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recordDefault",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerOperator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "reputationScore",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "operators", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordCompletion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordCycle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordDefault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reputationScore",
    data: BytesLike
  ): Result;
}

export namespace CycleCompletedEvent {
  export type InputTuple = [operator: AddressLike];
  export type OutputTuple = [operator: string];
  export interface OutputObject {
    operator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CycleDefaultedEvent {
  export type InputTuple = [operator: AddressLike];
  export type OutputTuple = [operator: string];
  export interface OutputObject {
    operator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CycleRecordedEvent {
  export type InputTuple = [operator: AddressLike, capital: BigNumberish];
  export type OutputTuple = [operator: string, capital: bigint];
  export interface OutputObject {
    operator: string;
    capital: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OperatorRegisteredEvent {
  export type InputTuple = [operator: AddressLike];
  export type OutputTuple = [operator: string];
  export interface OutputObject {
    operator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface OperatorRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): OperatorRegistry;
  waitForDeployment(): Promise<this>;

  interface: OperatorRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  operators: TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, bigint, bigint, bigint, bigint] & {
        registered: boolean;
        cyclesCreated: bigint;
        cyclesCompleted: bigint;
        cyclesDefaulted: bigint;
        totalCapitalRaised: bigint;
      }
    ],
    "view"
  >;

  recordCompletion: TypedContractMethod<
    [operator: AddressLike],
    [void],
    "nonpayable"
  >;

  recordCycle: TypedContractMethod<
    [operator: AddressLike, capital: BigNumberish],
    [void],
    "nonpayable"
  >;

  recordDefault: TypedContractMethod<
    [operator: AddressLike],
    [void],
    "nonpayable"
  >;

  registerOperator: TypedContractMethod<
    [operator: AddressLike],
    [void],
    "nonpayable"
  >;

  reputationScore: TypedContractMethod<
    [operator: AddressLike],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "operators"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, bigint, bigint, bigint, bigint] & {
        registered: boolean;
        cyclesCreated: bigint;
        cyclesCompleted: bigint;
        cyclesDefaulted: bigint;
        totalCapitalRaised: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "recordCompletion"
  ): TypedContractMethod<[operator: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "recordCycle"
  ): TypedContractMethod<
    [operator: AddressLike, capital: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recordDefault"
  ): TypedContractMethod<[operator: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registerOperator"
  ): TypedContractMethod<[operator: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reputationScore"
  ): TypedContractMethod<[operator: AddressLike], [bigint], "view">;

  getEvent(
    key: "CycleCompleted"
  ): TypedContractEvent<
    CycleCompletedEvent.InputTuple,
    CycleCompletedEvent.OutputTuple,
    CycleCompletedEvent.OutputObject
  >;
  getEvent(
    key: "CycleDefaulted"
  ): TypedContractEvent<
    CycleDefaultedEvent.InputTuple,
    CycleDefaultedEvent.OutputTuple,
    CycleDefaultedEvent.OutputObject
  >;
  getEvent(
    key: "CycleRecorded"
  ): TypedContractEvent<
    CycleRecordedEvent.InputTuple,
    CycleRecordedEvent.OutputTuple,
    CycleRecordedEvent.OutputObject
  >;
  getEvent(
    key: "OperatorRegistered"
  ): TypedContractEvent<
    OperatorRegisteredEvent.InputTuple,
    OperatorRegisteredEvent.OutputTuple,
    OperatorRegisteredEvent.OutputObject
  >;

  filters: {
    "CycleCompleted(address)": TypedContractEvent<
      CycleCompletedEvent.InputTuple,
      CycleCompletedEvent.OutputTuple,
      CycleCompletedEvent.OutputObject
    >;
    CycleCompleted: TypedContractEvent<
      CycleCompletedEvent.InputTuple,
      CycleCompletedEvent.OutputTuple,
      CycleCompletedEvent.OutputObject
    >;

    "CycleDefaulted(address)": TypedContractEvent<
      CycleDefaultedEvent.InputTuple,
      CycleDefaultedEvent.OutputTuple,
      CycleDefaultedEvent.OutputObject
    >;
    CycleDefaulted: TypedContractEvent<
      CycleDefaultedEvent.InputTuple,
      CycleDefaultedEvent.OutputTuple,
      CycleDefaultedEvent.OutputObject
    >;

    "CycleRecorded(address,uint256)": TypedContractEvent<
      CycleRecordedEvent.InputTuple,
      CycleRecordedEvent.OutputTuple,
      CycleRecordedEvent.OutputObject
    >;
    CycleRecorded: TypedContractEvent<
      CycleRecordedEvent.InputTuple,
      CycleRecordedEvent.OutputTuple,
      CycleRecordedEvent.OutputObject
    >;

    "OperatorRegistered(address)": TypedContractEvent<
      OperatorRegisteredEvent.InputTuple,
      OperatorRegisteredEvent.OutputTuple,
      OperatorRegisteredEvent.OutputObject
    >;
    OperatorRegistered: TypedContractEvent<
      OperatorRegisteredEvent.InputTuple,
      OperatorRegisteredEvent.OutputTuple,
      OperatorRegisteredEvent.OutputObject
    >;
  };
}
