/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface VerifierRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "activeVerifierCount"
      | "approvalCount"
      | "approvals"
      | "approveMilestone"
      | "claimRewards"
      | "getVerifierList"
      | "minimumStake"
      | "owner"
      | "quorum"
      | "quorumReached"
      | "receiveVerifierReward"
      | "registerVerifier"
      | "renounceOwnership"
      | "setMinimumStake"
      | "setQuorum"
      | "slashVerifier"
      | "stablecoin"
      | "transferOwnership"
      | "unstake"
      | "verifierActive"
      | "verifierList"
      | "verifiers"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "MilestoneApproved"
      | "OwnershipTransferred"
      | "RewardClaimed"
      | "RewardReceived"
      | "StakeSlashed"
      | "VerifierRegistered"
      | "VerifierUnstaked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "activeVerifierCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "approvalCount",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "approvals",
    values: [AddressLike, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "approveMilestone",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimRewards",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getVerifierList",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minimumStake",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "quorum", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "quorumReached",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "receiveVerifierReward",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerVerifier",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setMinimumStake",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setQuorum",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "slashVerifier",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "stablecoin",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unstake", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "verifierActive",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifierList",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "verifiers",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "activeVerifierCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approvalCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "approvals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "approveMilestone",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVerifierList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minimumStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "quorum", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "quorumReached",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "receiveVerifierReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMinimumStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setQuorum", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "slashVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stablecoin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unstake", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifierActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifierList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verifiers", data: BytesLike): Result;
}

export namespace MilestoneApprovedEvent {
  export type InputTuple = [
    cycle: AddressLike,
    milestone: BigNumberish,
    v: AddressLike
  ];
  export type OutputTuple = [cycle: string, milestone: bigint, v: string];
  export interface OutputObject {
    cycle: string;
    milestone: bigint;
    v: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardClaimedEvent {
  export type InputTuple = [v: AddressLike, amount: BigNumberish];
  export type OutputTuple = [v: string, amount: bigint];
  export interface OutputObject {
    v: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardReceivedEvent {
  export type InputTuple = [
    total: BigNumberish,
    perVerifier: BigNumberish,
    count: BigNumberish
  ];
  export type OutputTuple = [total: bigint, perVerifier: bigint, count: bigint];
  export interface OutputObject {
    total: bigint;
    perVerifier: bigint;
    count: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakeSlashedEvent {
  export type InputTuple = [v: AddressLike, amount: BigNumberish];
  export type OutputTuple = [v: string, amount: bigint];
  export interface OutputObject {
    v: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerifierRegisteredEvent {
  export type InputTuple = [v: AddressLike, stake: BigNumberish];
  export type OutputTuple = [v: string, stake: bigint];
  export interface OutputObject {
    v: string;
    stake: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerifierUnstakedEvent {
  export type InputTuple = [v: AddressLike, amount: BigNumberish];
  export type OutputTuple = [v: string, amount: bigint];
  export interface OutputObject {
    v: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface VerifierRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): VerifierRegistry;
  waitForDeployment(): Promise<this>;

  interface: VerifierRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  activeVerifierCount: TypedContractMethod<[], [bigint], "view">;

  approvalCount: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  approvals: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish, arg2: AddressLike],
    [boolean],
    "view"
  >;

  approveMilestone: TypedContractMethod<
    [cycle: AddressLike, milestoneId: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimRewards: TypedContractMethod<[], [void], "nonpayable">;

  getVerifierList: TypedContractMethod<[], [string[]], "view">;

  minimumStake: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  quorum: TypedContractMethod<[], [bigint], "view">;

  quorumReached: TypedContractMethod<
    [cycle: AddressLike, milestoneId: BigNumberish],
    [boolean],
    "view"
  >;

  receiveVerifierReward: TypedContractMethod<
    [totalAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  registerVerifier: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setMinimumStake: TypedContractMethod<[m: BigNumberish], [void], "nonpayable">;

  setQuorum: TypedContractMethod<[q: BigNumberish], [void], "nonpayable">;

  slashVerifier: TypedContractMethod<
    [verifier: AddressLike],
    [void],
    "nonpayable"
  >;

  stablecoin: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unstake: TypedContractMethod<[], [void], "nonpayable">;

  verifierActive: TypedContractMethod<[v: AddressLike], [boolean], "view">;

  verifierList: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  verifiers: TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, bigint, bigint, bigint, bigint] & {
        active: boolean;
        stake: bigint;
        pendingReward: bigint;
        totalEarned: bigint;
        approvalsGiven: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "activeVerifierCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "approvalCount"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "approvals"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish, arg2: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "approveMilestone"
  ): TypedContractMethod<
    [cycle: AddressLike, milestoneId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claimRewards"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getVerifierList"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "minimumStake"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "quorum"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "quorumReached"
  ): TypedContractMethod<
    [cycle: AddressLike, milestoneId: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "receiveVerifierReward"
  ): TypedContractMethod<[totalAmount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registerVerifier"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMinimumStake"
  ): TypedContractMethod<[m: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setQuorum"
  ): TypedContractMethod<[q: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "slashVerifier"
  ): TypedContractMethod<[verifier: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stablecoin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unstake"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifierActive"
  ): TypedContractMethod<[v: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "verifierList"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "verifiers"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, bigint, bigint, bigint, bigint] & {
        active: boolean;
        stake: bigint;
        pendingReward: bigint;
        totalEarned: bigint;
        approvalsGiven: bigint;
      }
    ],
    "view"
  >;

  getEvent(
    key: "MilestoneApproved"
  ): TypedContractEvent<
    MilestoneApprovedEvent.InputTuple,
    MilestoneApprovedEvent.OutputTuple,
    MilestoneApprovedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RewardClaimed"
  ): TypedContractEvent<
    RewardClaimedEvent.InputTuple,
    RewardClaimedEvent.OutputTuple,
    RewardClaimedEvent.OutputObject
  >;
  getEvent(
    key: "RewardReceived"
  ): TypedContractEvent<
    RewardReceivedEvent.InputTuple,
    RewardReceivedEvent.OutputTuple,
    RewardReceivedEvent.OutputObject
  >;
  getEvent(
    key: "StakeSlashed"
  ): TypedContractEvent<
    StakeSlashedEvent.InputTuple,
    StakeSlashedEvent.OutputTuple,
    StakeSlashedEvent.OutputObject
  >;
  getEvent(
    key: "VerifierRegistered"
  ): TypedContractEvent<
    VerifierRegisteredEvent.InputTuple,
    VerifierRegisteredEvent.OutputTuple,
    VerifierRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "VerifierUnstaked"
  ): TypedContractEvent<
    VerifierUnstakedEvent.InputTuple,
    VerifierUnstakedEvent.OutputTuple,
    VerifierUnstakedEvent.OutputObject
  >;

  filters: {
    "MilestoneApproved(address,uint8,address)": TypedContractEvent<
      MilestoneApprovedEvent.InputTuple,
      MilestoneApprovedEvent.OutputTuple,
      MilestoneApprovedEvent.OutputObject
    >;
    MilestoneApproved: TypedContractEvent<
      MilestoneApprovedEvent.InputTuple,
      MilestoneApprovedEvent.OutputTuple,
      MilestoneApprovedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RewardClaimed(address,uint256)": TypedContractEvent<
      RewardClaimedEvent.InputTuple,
      RewardClaimedEvent.OutputTuple,
      RewardClaimedEvent.OutputObject
    >;
    RewardClaimed: TypedContractEvent<
      RewardClaimedEvent.InputTuple,
      RewardClaimedEvent.OutputTuple,
      RewardClaimedEvent.OutputObject
    >;

    "RewardReceived(uint256,uint256,uint256)": TypedContractEvent<
      RewardReceivedEvent.InputTuple,
      RewardReceivedEvent.OutputTuple,
      RewardReceivedEvent.OutputObject
    >;
    RewardReceived: TypedContractEvent<
      RewardReceivedEvent.InputTuple,
      RewardReceivedEvent.OutputTuple,
      RewardReceivedEvent.OutputObject
    >;

    "StakeSlashed(address,uint256)": TypedContractEvent<
      StakeSlashedEvent.InputTuple,
      StakeSlashedEvent.OutputTuple,
      StakeSlashedEvent.OutputObject
    >;
    StakeSlashed: TypedContractEvent<
      StakeSlashedEvent.InputTuple,
      StakeSlashedEvent.OutputTuple,
      StakeSlashedEvent.OutputObject
    >;

    "VerifierRegistered(address,uint256)": TypedContractEvent<
      VerifierRegisteredEvent.InputTuple,
      VerifierRegisteredEvent.OutputTuple,
      VerifierRegisteredEvent.OutputObject
    >;
    VerifierRegistered: TypedContractEvent<
      VerifierRegisteredEvent.InputTuple,
      VerifierRegisteredEvent.OutputTuple,
      VerifierRegisteredEvent.OutputObject
    >;

    "VerifierUnstaked(address,uint256)": TypedContractEvent<
      VerifierUnstakedEvent.InputTuple,
      VerifierUnstakedEvent.OutputTuple,
      VerifierUnstakedEvent.OutputObject
    >;
    VerifierUnstaked: TypedContractEvent<
      VerifierUnstakedEvent.InputTuple,
      VerifierUnstakedEvent.OutputTuple,
      VerifierUnstakedEvent.OutputObject
    >;
  };
}
