/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface YieldOracleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "estimates"
      | "getEstimate"
      | "owner"
      | "renounceOwnership"
      | "transferOwnership"
      | "updateEstimate"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "OwnershipTransferred" | "YieldUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "estimates",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEstimate",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateEstimate",
    values: [AddressLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "estimates", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getEstimate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateEstimate",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace YieldUpdatedEvent {
  export type InputTuple = [
    cycle: AddressLike,
    revenue: BigNumberish,
    profit: BigNumberish,
    roi: BigNumberish,
    risk: BigNumberish
  ];
  export type OutputTuple = [
    cycle: string,
    revenue: bigint,
    profit: bigint,
    roi: bigint,
    risk: bigint
  ];
  export interface OutputObject {
    cycle: string;
    revenue: bigint;
    profit: bigint;
    roi: bigint;
    risk: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface YieldOracle extends BaseContract {
  connect(runner?: ContractRunner | null): YieldOracle;
  waitForDeployment(): Promise<this>;

  interface: YieldOracleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  estimates: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, boolean] & {
        expectedRevenue: bigint;
        estimatedCost: bigint;
        estimatedProfit: bigint;
        estimatedROI: bigint;
        riskScore: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  getEstimate: TypedContractMethod<
    [cycle: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        revenue: bigint;
        cost: bigint;
        profit: bigint;
        roi: bigint;
        risk: bigint;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateEstimate: TypedContractMethod<
    [
      cycle: AddressLike,
      expectedRevenue: BigNumberish,
      estimatedCost: BigNumberish,
      riskScore: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "estimates"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, boolean] & {
        expectedRevenue: bigint;
        estimatedCost: bigint;
        estimatedProfit: bigint;
        estimatedROI: bigint;
        riskScore: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEstimate"
  ): TypedContractMethod<
    [cycle: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        revenue: bigint;
        cost: bigint;
        profit: bigint;
        roi: bigint;
        risk: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateEstimate"
  ): TypedContractMethod<
    [
      cycle: AddressLike,
      expectedRevenue: BigNumberish,
      estimatedCost: BigNumberish,
      riskScore: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "YieldUpdated"
  ): TypedContractEvent<
    YieldUpdatedEvent.InputTuple,
    YieldUpdatedEvent.OutputTuple,
    YieldUpdatedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "YieldUpdated(address,uint256,uint256,uint256,uint8)": TypedContractEvent<
      YieldUpdatedEvent.InputTuple,
      YieldUpdatedEvent.OutputTuple,
      YieldUpdatedEvent.OutputObject
    >;
    YieldUpdated: TypedContractEvent<
      YieldUpdatedEvent.InputTuple,
      YieldUpdatedEvent.OutputTuple,
      YieldUpdatedEvent.OutputObject
    >;
  };
}
