/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MockDexFactory } from "./MockDexFactory";
export type { MockDexRouter } from "./MockDexRouter";
