/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace CycleMarketplace {
  export type CycleInfoStruct = {
    cycle: AddressLike;
    operator: AddressLike;
    name: string;
    category: string;
    location: string;
    capitalRequired: BigNumberish;
    duration: BigNumberish;
  };

  export type CycleInfoStructOutput = [
    cycle: string,
    operator: string,
    name: string,
    category: string,
    location: string,
    capitalRequired: bigint,
    duration: bigint
  ] & {
    cycle: string;
    operator: string;
    name: string;
    category: string;
    location: string;
    capitalRequired: bigint;
    duration: bigint;
  };
}

export interface CycleMarketplaceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "cycles"
      | "getAllCycles"
      | "getOperatorCycles"
      | "listCycle"
      | "operatorCycles"
      | "totalCycles"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "CycleListed"): EventFragment;

  encodeFunctionData(
    functionFragment: "cycles",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllCycles",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getOperatorCycles",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "listCycle",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "operatorCycles",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalCycles",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "cycles", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllCycles",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOperatorCycles",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "listCycle", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "operatorCycles",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalCycles",
    data: BytesLike
  ): Result;
}

export namespace CycleListedEvent {
  export type InputTuple = [cycle: AddressLike, operator: AddressLike];
  export type OutputTuple = [cycle: string, operator: string];
  export interface OutputObject {
    cycle: string;
    operator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CycleMarketplace extends BaseContract {
  connect(runner?: ContractRunner | null): CycleMarketplace;
  waitForDeployment(): Promise<this>;

  interface: CycleMarketplaceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  cycles: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, string, string, bigint, bigint] & {
        cycle: string;
        operator: string;
        name: string;
        category: string;
        location: string;
        capitalRequired: bigint;
        duration: bigint;
      }
    ],
    "view"
  >;

  getAllCycles: TypedContractMethod<
    [],
    [CycleMarketplace.CycleInfoStructOutput[]],
    "view"
  >;

  getOperatorCycles: TypedContractMethod<
    [operator: AddressLike],
    [bigint[]],
    "view"
  >;

  listCycle: TypedContractMethod<
    [cycleAddress: AddressLike, operator: AddressLike],
    [void],
    "nonpayable"
  >;

  operatorCycles: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  totalCycles: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "cycles"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, string, string, bigint, bigint] & {
        cycle: string;
        operator: string;
        name: string;
        category: string;
        location: string;
        capitalRequired: bigint;
        duration: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAllCycles"
  ): TypedContractMethod<
    [],
    [CycleMarketplace.CycleInfoStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOperatorCycles"
  ): TypedContractMethod<[operator: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "listCycle"
  ): TypedContractMethod<
    [cycleAddress: AddressLike, operator: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "operatorCycles"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "totalCycles"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "CycleListed"
  ): TypedContractEvent<
    CycleListedEvent.InputTuple,
    CycleListedEvent.OutputTuple,
    CycleListedEvent.OutputObject
  >;

  filters: {
    "CycleListed(address,address)": TypedContractEvent<
      CycleListedEvent.InputTuple,
      CycleListedEvent.OutputTuple,
      CycleListedEvent.OutputObject
    >;
    CycleListed: TypedContractEvent<
      CycleListedEvent.InputTuple,
      CycleListedEvent.OutputTuple,
      CycleListedEvent.OutputObject
    >;
  };
}
