/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IReserveCompensatedCycle } from "./IReserveCompensatedCycle";
export type { ReservePool } from "./ReservePool";
