/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MockDexFactory__factory } from "./MockDexFactory__factory";
export { MockDexRouter__factory } from "./MockDexRouter__factory";
