/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ILiquidityVaultLike,
  ILiquidityVaultLikeInterface,
} from "../../../contracts/LiquidityManager.sol/ILiquidityVaultLike";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "requestFunds",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ILiquidityVaultLike__factory {
  static readonly abi = _abi;
  static createInterface(): ILiquidityVaultLikeInterface {
    return new Interface(_abi) as ILiquidityVaultLikeInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ILiquidityVaultLike {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as ILiquidityVaultLike;
  }
}
