/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ILiquidityManager,
  ILiquidityManagerInterface,
} from "../../../contracts/ProductionCycle.sol/ILiquidityManager";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "cycle",
        type: "address",
      },
    ],
    name: "onFundingComplete",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ILiquidityManager__factory {
  static readonly abi = _abi;
  static createInterface(): ILiquidityManagerInterface {
    return new Interface(_abi) as ILiquidityManagerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ILiquidityManager {
    return new Contract(address, _abi, runner) as unknown as ILiquidityManager;
  }
}
