/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IVerifierRegistry,
  IVerifierRegistryInterface,
} from "../../../contracts/ProductionCycle.sol/IVerifierRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "cycle",
        type: "address",
      },
      {
        internalType: "uint8",
        name: "milestoneId",
        type: "uint8",
      },
    ],
    name: "quorumReached",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "cycle",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "totalAmount",
        type: "uint256",
      },
    ],
    name: "receiveVerifierReward",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IVerifierRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IVerifierRegistryInterface {
    return new Interface(_abi) as IVerifierRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IVerifierRegistry {
    return new Contract(address, _abi, runner) as unknown as IVerifierRegistry;
  }
}
