/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ICollateralVault2,
  ICollateralVault2Interface,
} from "../../../contracts/ProductionCycleFactoryV2.sol/ICollateralVault2";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "operator",
        type: "address",
      },
    ],
    name: "collateralBalance",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "cycle",
        type: "address",
      },
      {
        internalType: "bool",
        name: "allowed",
        type: "bool",
      },
    ],
    name: "registerTrustedCycle",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ICollateralVault2__factory {
  static readonly abi = _abi;
  static createInterface(): ICollateralVault2Interface {
    return new Interface(_abi) as ICollateralVault2Interface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ICollateralVault2 {
    return new Contract(address, _abi, runner) as unknown as ICollateralVault2;
  }
}
