/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ILiquidityVaultDepositor,
  ILiquidityVaultDepositorInterface,
} from "../../../contracts/ProductionCycleFactoryV2.sol/ILiquidityVaultDepositor";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "depositFrom",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ILiquidityVaultDepositor__factory {
  static readonly abi = _abi;
  static createInterface(): ILiquidityVaultDepositorInterface {
    return new Interface(_abi) as ILiquidityVaultDepositorInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ILiquidityVaultDepositor {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as ILiquidityVaultDepositor;
  }
}
