/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IProductionCycle,
  IProductionCycleInterface,
} from "../../../contracts/PortfolioVault.sol/IProductionCycle";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "invest",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IProductionCycle__factory {
  static readonly abi = _abi;
  static createInterface(): IProductionCycleInterface {
    return new Interface(_abi) as IProductionCycleInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IProductionCycle {
    return new Contract(address, _abi, runner) as unknown as IProductionCycle;
  }
}
