/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface LiquidityManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_SEED_BPS"
      | "dexFactory"
      | "dexRouter"
      | "factory"
      | "fund"
      | "launches"
      | "onFundingComplete"
      | "owner"
      | "registerCycle"
      | "renounceOwnership"
      | "rescueAsset"
      | "retryLiquidityLaunch"
      | "setDex"
      | "setFactory"
      | "setSeedConfig"
      | "setVault"
      | "stableSeedBps"
      | "stablecoin"
      | "tokenSeedBps"
      | "transferOwnership"
      | "vault"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AssetRescued"
      | "CycleRegistered"
      | "DexSet"
      | "FactorySet"
      | "LiquidityLaunchFailed"
      | "LiquidityLaunched"
      | "OwnershipTransferred"
      | "SeedConfigUpdated"
      | "SeedInvestmentExecuted"
      | "StablecoinFunded"
      | "VaultSet"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MAX_SEED_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "dexFactory",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "dexRouter", values?: undefined): string;
  encodeFunctionData(functionFragment: "factory", values?: undefined): string;
  encodeFunctionData(functionFragment: "fund", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "launches",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "onFundingComplete",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerCycle",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rescueAsset",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "retryLiquidityLaunch",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setDex",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setFactory",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setSeedConfig",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setVault",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "stableSeedBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "stablecoin",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tokenSeedBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "vault", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "MAX_SEED_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "dexFactory", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "dexRouter", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "factory", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fund", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "launches", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "onFundingComplete",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerCycle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rescueAsset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "retryLiquidityLaunch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setDex", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setFactory", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setSeedConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setVault", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "stableSeedBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stablecoin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tokenSeedBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vault", data: BytesLike): Result;
}

export namespace AssetRescuedEvent {
  export type InputTuple = [
    token: AddressLike,
    to: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [token: string, to: string, amount: bigint];
  export interface OutputObject {
    token: string;
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CycleRegisteredEvent {
  export type InputTuple = [
    cycle: AddressLike,
    tokenInvestmentAmount: BigNumberish,
    stableLiquidityAmount: BigNumberish
  ];
  export type OutputTuple = [
    cycle: string,
    tokenInvestmentAmount: bigint,
    stableLiquidityAmount: bigint
  ];
  export interface OutputObject {
    cycle: string;
    tokenInvestmentAmount: bigint;
    stableLiquidityAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DexSetEvent {
  export type InputTuple = [dexFactory: AddressLike, dexRouter: AddressLike];
  export type OutputTuple = [dexFactory: string, dexRouter: string];
  export interface OutputObject {
    dexFactory: string;
    dexRouter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FactorySetEvent {
  export type InputTuple = [factory: AddressLike];
  export type OutputTuple = [factory: string];
  export interface OutputObject {
    factory: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidityLaunchFailedEvent {
  export type InputTuple = [cycle: AddressLike, reason: string];
  export type OutputTuple = [cycle: string, reason: string];
  export interface OutputObject {
    cycle: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidityLaunchedEvent {
  export type InputTuple = [
    cycle: AddressLike,
    token: AddressLike,
    tokenAmount: BigNumberish,
    stableAmount: BigNumberish
  ];
  export type OutputTuple = [
    cycle: string,
    token: string,
    tokenAmount: bigint,
    stableAmount: bigint
  ];
  export interface OutputObject {
    cycle: string;
    token: string;
    tokenAmount: bigint;
    stableAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SeedConfigUpdatedEvent {
  export type InputTuple = [
    tokenSeedBps: BigNumberish,
    stableSeedBps: BigNumberish
  ];
  export type OutputTuple = [tokenSeedBps: bigint, stableSeedBps: bigint];
  export interface OutputObject {
    tokenSeedBps: bigint;
    stableSeedBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SeedInvestmentExecutedEvent {
  export type InputTuple = [cycle: AddressLike, amount: BigNumberish];
  export type OutputTuple = [cycle: string, amount: bigint];
  export interface OutputObject {
    cycle: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StablecoinFundedEvent {
  export type InputTuple = [from: AddressLike, amount: BigNumberish];
  export type OutputTuple = [from: string, amount: bigint];
  export interface OutputObject {
    from: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultSetEvent {
  export type InputTuple = [vault: AddressLike];
  export type OutputTuple = [vault: string];
  export interface OutputObject {
    vault: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LiquidityManager extends BaseContract {
  connect(runner?: ContractRunner | null): LiquidityManager;
  waitForDeployment(): Promise<this>;

  interface: LiquidityManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_SEED_BPS: TypedContractMethod<[], [bigint], "view">;

  dexFactory: TypedContractMethod<[], [string], "view">;

  dexRouter: TypedContractMethod<[], [string], "view">;

  factory: TypedContractMethod<[], [string], "view">;

  fund: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  launches: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, boolean, boolean, boolean] & {
        tokenInvestmentAmount: bigint;
        stableLiquidityAmount: bigint;
        invested: boolean;
        launched: boolean;
        enabled: boolean;
      }
    ],
    "view"
  >;

  onFundingComplete: TypedContractMethod<
    [cycle: AddressLike],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  registerCycle: TypedContractMethod<
    [cycle: AddressLike, capitalRequired: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  rescueAsset: TypedContractMethod<
    [token: AddressLike, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  retryLiquidityLaunch: TypedContractMethod<
    [cycle: AddressLike],
    [void],
    "nonpayable"
  >;

  setDex: TypedContractMethod<
    [_dexFactory: AddressLike, _dexRouter: AddressLike],
    [void],
    "nonpayable"
  >;

  setFactory: TypedContractMethod<
    [_factory: AddressLike],
    [void],
    "nonpayable"
  >;

  setSeedConfig: TypedContractMethod<
    [_tokenSeedBps: BigNumberish, _stableSeedBps: BigNumberish],
    [void],
    "nonpayable"
  >;

  setVault: TypedContractMethod<[_vault: AddressLike], [void], "nonpayable">;

  stableSeedBps: TypedContractMethod<[], [bigint], "view">;

  stablecoin: TypedContractMethod<[], [string], "view">;

  tokenSeedBps: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  vault: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_SEED_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "dexFactory"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "dexRouter"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "factory"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "fund"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "launches"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, boolean, boolean, boolean] & {
        tokenInvestmentAmount: bigint;
        stableLiquidityAmount: bigint;
        invested: boolean;
        launched: boolean;
        enabled: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "onFundingComplete"
  ): TypedContractMethod<[cycle: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerCycle"
  ): TypedContractMethod<
    [cycle: AddressLike, capitalRequired: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rescueAsset"
  ): TypedContractMethod<
    [token: AddressLike, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "retryLiquidityLaunch"
  ): TypedContractMethod<[cycle: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setDex"
  ): TypedContractMethod<
    [_dexFactory: AddressLike, _dexRouter: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setFactory"
  ): TypedContractMethod<[_factory: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setSeedConfig"
  ): TypedContractMethod<
    [_tokenSeedBps: BigNumberish, _stableSeedBps: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setVault"
  ): TypedContractMethod<[_vault: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stableSeedBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "stablecoin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "tokenSeedBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "vault"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "AssetRescued"
  ): TypedContractEvent<
    AssetRescuedEvent.InputTuple,
    AssetRescuedEvent.OutputTuple,
    AssetRescuedEvent.OutputObject
  >;
  getEvent(
    key: "CycleRegistered"
  ): TypedContractEvent<
    CycleRegisteredEvent.InputTuple,
    CycleRegisteredEvent.OutputTuple,
    CycleRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "DexSet"
  ): TypedContractEvent<
    DexSetEvent.InputTuple,
    DexSetEvent.OutputTuple,
    DexSetEvent.OutputObject
  >;
  getEvent(
    key: "FactorySet"
  ): TypedContractEvent<
    FactorySetEvent.InputTuple,
    FactorySetEvent.OutputTuple,
    FactorySetEvent.OutputObject
  >;
  getEvent(
    key: "LiquidityLaunchFailed"
  ): TypedContractEvent<
    LiquidityLaunchFailedEvent.InputTuple,
    LiquidityLaunchFailedEvent.OutputTuple,
    LiquidityLaunchFailedEvent.OutputObject
  >;
  getEvent(
    key: "LiquidityLaunched"
  ): TypedContractEvent<
    LiquidityLaunchedEvent.InputTuple,
    LiquidityLaunchedEvent.OutputTuple,
    LiquidityLaunchedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "SeedConfigUpdated"
  ): TypedContractEvent<
    SeedConfigUpdatedEvent.InputTuple,
    SeedConfigUpdatedEvent.OutputTuple,
    SeedConfigUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "SeedInvestmentExecuted"
  ): TypedContractEvent<
    SeedInvestmentExecutedEvent.InputTuple,
    SeedInvestmentExecutedEvent.OutputTuple,
    SeedInvestmentExecutedEvent.OutputObject
  >;
  getEvent(
    key: "StablecoinFunded"
  ): TypedContractEvent<
    StablecoinFundedEvent.InputTuple,
    StablecoinFundedEvent.OutputTuple,
    StablecoinFundedEvent.OutputObject
  >;
  getEvent(
    key: "VaultSet"
  ): TypedContractEvent<
    VaultSetEvent.InputTuple,
    VaultSetEvent.OutputTuple,
    VaultSetEvent.OutputObject
  >;

  filters: {
    "AssetRescued(address,address,uint256)": TypedContractEvent<
      AssetRescuedEvent.InputTuple,
      AssetRescuedEvent.OutputTuple,
      AssetRescuedEvent.OutputObject
    >;
    AssetRescued: TypedContractEvent<
      AssetRescuedEvent.InputTuple,
      AssetRescuedEvent.OutputTuple,
      AssetRescuedEvent.OutputObject
    >;

    "CycleRegistered(address,uint256,uint256)": TypedContractEvent<
      CycleRegisteredEvent.InputTuple,
      CycleRegisteredEvent.OutputTuple,
      CycleRegisteredEvent.OutputObject
    >;
    CycleRegistered: TypedContractEvent<
      CycleRegisteredEvent.InputTuple,
      CycleRegisteredEvent.OutputTuple,
      CycleRegisteredEvent.OutputObject
    >;

    "DexSet(address,address)": TypedContractEvent<
      DexSetEvent.InputTuple,
      DexSetEvent.OutputTuple,
      DexSetEvent.OutputObject
    >;
    DexSet: TypedContractEvent<
      DexSetEvent.InputTuple,
      DexSetEvent.OutputTuple,
      DexSetEvent.OutputObject
    >;

    "FactorySet(address)": TypedContractEvent<
      FactorySetEvent.InputTuple,
      FactorySetEvent.OutputTuple,
      FactorySetEvent.OutputObject
    >;
    FactorySet: TypedContractEvent<
      FactorySetEvent.InputTuple,
      FactorySetEvent.OutputTuple,
      FactorySetEvent.OutputObject
    >;

    "LiquidityLaunchFailed(address,string)": TypedContractEvent<
      LiquidityLaunchFailedEvent.InputTuple,
      LiquidityLaunchFailedEvent.OutputTuple,
      LiquidityLaunchFailedEvent.OutputObject
    >;
    LiquidityLaunchFailed: TypedContractEvent<
      LiquidityLaunchFailedEvent.InputTuple,
      LiquidityLaunchFailedEvent.OutputTuple,
      LiquidityLaunchFailedEvent.OutputObject
    >;

    "LiquidityLaunched(address,address,uint256,uint256)": TypedContractEvent<
      LiquidityLaunchedEvent.InputTuple,
      LiquidityLaunchedEvent.OutputTuple,
      LiquidityLaunchedEvent.OutputObject
    >;
    LiquidityLaunched: TypedContractEvent<
      LiquidityLaunchedEvent.InputTuple,
      LiquidityLaunchedEvent.OutputTuple,
      LiquidityLaunchedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "SeedConfigUpdated(uint16,uint16)": TypedContractEvent<
      SeedConfigUpdatedEvent.InputTuple,
      SeedConfigUpdatedEvent.OutputTuple,
      SeedConfigUpdatedEvent.OutputObject
    >;
    SeedConfigUpdated: TypedContractEvent<
      SeedConfigUpdatedEvent.InputTuple,
      SeedConfigUpdatedEvent.OutputTuple,
      SeedConfigUpdatedEvent.OutputObject
    >;

    "SeedInvestmentExecuted(address,uint256)": TypedContractEvent<
      SeedInvestmentExecutedEvent.InputTuple,
      SeedInvestmentExecutedEvent.OutputTuple,
      SeedInvestmentExecutedEvent.OutputObject
    >;
    SeedInvestmentExecuted: TypedContractEvent<
      SeedInvestmentExecutedEvent.InputTuple,
      SeedInvestmentExecutedEvent.OutputTuple,
      SeedInvestmentExecutedEvent.OutputObject
    >;

    "StablecoinFunded(address,uint256)": TypedContractEvent<
      StablecoinFundedEvent.InputTuple,
      StablecoinFundedEvent.OutputTuple,
      StablecoinFundedEvent.OutputObject
    >;
    StablecoinFunded: TypedContractEvent<
      StablecoinFundedEvent.InputTuple,
      StablecoinFundedEvent.OutputTuple,
      StablecoinFundedEvent.OutputObject
    >;

    "VaultSet(address)": TypedContractEvent<
      VaultSetEvent.InputTuple,
      VaultSetEvent.OutputTuple,
      VaultSetEvent.OutputObject
    >;
    VaultSet: TypedContractEvent<
      VaultSetEvent.InputTuple,
      VaultSetEvent.OutputTuple,
      VaultSetEvent.OutputObject
    >;
  };
}
