/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ICycleFactoryReader,
  ICycleFactoryReaderInterface,
} from "../../../contracts/VerifierRegistry.sol/ICycleFactoryReader";

const _abi = [
  {
    inputs: [],
    name: "getAllCycles",
    outputs: [
      {
        internalType: "address[]",
        name: "",
        type: "address[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ICycleFactoryReader__factory {
  static readonly abi = _abi;
  static createInterface(): ICycleFactoryReaderInterface {
    return new Interface(_abi) as ICycleFactoryReaderInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ICycleFactoryReader {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as ICycleFactoryReader;
  }
}
