/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ICycleStateReader,
  ICycleStateReaderInterface,
} from "../../../contracts/VerifierRegistry.sol/ICycleStateReader";

const _abi = [
  {
    inputs: [],
    name: "state",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ICycleStateReader__factory {
  static readonly abi = _abi;
  static createInterface(): ICycleStateReaderInterface {
    return new Interface(_abi) as ICycleStateReaderInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ICycleStateReader {
    return new Contract(address, _abi, runner) as unknown as ICycleStateReader;
  }
}
