import { ethers, network } from "hardhat"
import * as fs from "fs-extra"
import * as path from "path"

async function main() {
  const [deployer] = await ethers.getSigners()
  console.log("\nFundR V2 Upgrade Deployment")
  console.log("Deployer:", deployer.address)
  if (network.name === "arcTestnet") {
    throw new Error("deployV2.ts deploys mock USDC upgrade components. Use scripts/deploy.ts for Arc Testnet so the protocol uses Arc's real USDC address and 6-decimal accounting.")
  }

  const depPath = path.join(__dirname, `../deployments/${network.name}.json`)
  const existing = await fs.readJson(depPath)
  const addresses: Record<string, string> = { ...existing }

  const Faucet = await ethers.getContractFactory("MockUSDCFaucet")
  const faucet = await Faucet.deploy()
  await faucet.waitForDeployment()
  addresses.MockUSDCFaucet = await faucet.getAddress()

  const LiquidityVault = await ethers.getContractFactory("LiquidityVault")
  const liquidityVault = await LiquidityVault.deploy(addresses.MockUSDCFaucet)
  await liquidityVault.waitForDeployment()
  addresses.LiquidityVault = await liquidityVault.getAddress()

  const LiquidityManager = await ethers.getContractFactory("LiquidityManager")
  const liquidityManager = await LiquidityManager.deploy(addresses.MockUSDCFaucet)
  await liquidityManager.waitForDeployment()
  addresses.LiquidityManager = await liquidityManager.getAddress()

  const FactoryV2 = await ethers.getContractFactory("ProductionCycleFactoryV2")
  const factoryV2 = await FactoryV2.deploy(
    addresses.MockUSDCFaucet,
    existing.VerifierRegistry,
    existing.CollateralVault,
    existing.ReservePool,
    existing.ProtocolTreasury,
    addresses.LiquidityVault,
    addresses.LiquidityManager,
  )
  await factoryV2.waitForDeployment()
  addresses.ProductionCycleFactoryV2 = await factoryV2.getAddress()

  const verifierRegistry = await ethers.getContractAt("VerifierRegistry", existing.VerifierRegistry)
  await verifierRegistry.setFactory(addresses.ProductionCycleFactoryV2)
  await liquidityManager.setFactory(addresses.ProductionCycleFactoryV2)
  await liquidityManager.setVault(addresses.LiquidityVault)
  await liquidityVault.setLiquidityManager(addresses.LiquidityManager)

  const MarketV2 = await ethers.getContractFactory("CycleTokenMarketplaceV2")
  const marketV2 = await MarketV2.deploy(addresses.MockUSDCFaucet, existing.ProtocolTreasury)
  await marketV2.waitForDeployment()
  addresses.CycleTokenMarketplaceV2 = await marketV2.getAddress()

  await factoryV2.setApprovalMode(1, ethers.parseEther("1000"))
  await faucet.mint(existing.ReservePool, ethers.parseEther("50000"))

  await fs.writeJson(depPath, { ...addresses, updatedAt: new Date().toISOString(), deployer: deployer.address, network: network.name }, { spaces: 2 })

  const uiPath = path.join(__dirname, "../rwa-ui/constants/contracts.ts")
  if (await fs.pathExists(path.join(__dirname, "../rwa-ui"))) {
    const uiNetwork = network.name === "arcTestnet"
      ? {
          name: "Arc Testnet",
          chainId: 5042002,
          blockExplorer: "https://testnet.arcscan.app",
          blockExplorerName: "ArcScan",
          rpcUrl: "https://rpc.testnet.arc.network",
          nativeCurrency: { name: "USD Coin", symbol: "USDC", decimals: 18 },
          isTestnet: true,
        }
      : {
          name: "Base Sepolia",
          chainId: 84532,
          blockExplorer: "https://sepolia.basescan.org",
          blockExplorerName: "BaseScan",
          rpcUrl: "https://sepolia.base.org",
          nativeCurrency: { name: "Sepolia Ether", symbol: "ETH", decimals: 18 },
          isTestnet: true,
        }

    const uiContent = `// Auto-generated by deployV2.ts - ${new Date().toISOString()}

export const PROTOCOL_OWNER: \`0x\${string}\` =
  (process.env.NEXT_PUBLIC_PROTOCOL_OWNER as \`0x\${string}\`) ||
  "${deployer.address}"

export const CONTRACTS = {
  factory:           "${addresses.ProductionCycleFactoryV2}" as \`0x\${string}\`,
  stablecoin:        "${addresses.MockUSDCFaucet}" as \`0x\${string}\`,
  treasury:          "${existing.ProtocolTreasury}" as \`0x\${string}\`,
  reservePool:       "${existing.ReservePool}" as \`0x\${string}\`,
  verifierRegistry:  "${existing.VerifierRegistry}" as \`0x\${string}\`,
  collateralVault:   "${existing.CollateralVault}" as \`0x\${string}\`,
  yieldOracle:       "${existing.YieldOracle}" as \`0x\${string}\`,
  liquidityVault:    "${addresses.LiquidityVault}" as \`0x\${string}\`,
  liquidityManager:  "${addresses.LiquidityManager}" as \`0x\${string}\`,
  tokenMarketplace:  "${addresses.CycleTokenMarketplaceV2}" as \`0x\${string}\`,
} as const

export const NETWORK = {
  name:          "${uiNetwork.name}",
  chainId:       ${uiNetwork.chainId},
  blockExplorer: "${uiNetwork.blockExplorer}",
  blockExplorerName: "${uiNetwork.blockExplorerName}",
  rpcUrl:        "${uiNetwork.rpcUrl}",
  nativeCurrency: { name: "${uiNetwork.nativeCurrency.name}", symbol: "${uiNetwork.nativeCurrency.symbol}", decimals: ${uiNetwork.nativeCurrency.decimals} },
  isTestnet:     ${uiNetwork.isTestnet},
} as const

export const MILESTONE_LABELS = [
  { id: 0, label: "Production start",     pct: 40, description: "Initial capital released - production begins" },
  { id: 1, label: "Mid-cycle checkpoint", pct: 30, description: "Second tranche - confirmed mid-cycle progress" },
  { id: 2, label: "Harvest / completion", pct: 20, description: "Third tranche - product ready or delivered" },
  { id: 3, label: "Final settlement",     pct: 10, description: "Final tranche - buyer payment received" },
] as const

export const CYCLE_STATES: Record<number, string> = {
  0: "FUNDING",
  1: "ACTIVE",
  2: "HARVEST_SUBMITTED",
  3: "DISTRIBUTED",
  4: "DEFAULTED",
}

export const PROTOCOL_FEES = {
  defaultProtocolFee:    1,
  defaultReserveFee:     1,
  marketplaceTradingFee: 0.5,
} as const
`
    await fs.writeFile(uiPath, uiContent)
  }
}

main().catch((error) => {
  console.error(error)
  process.exit(1)
})
