/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IProductionCycleOperatorReader,
  IProductionCycleOperatorReaderInterface,
} from "../../../contracts/CollateralVault.sol/IProductionCycleOperatorReader";

const _abi = [
  {
    inputs: [],
    name: "operator",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IProductionCycleOperatorReader__factory {
  static readonly abi = _abi;
  static createInterface(): IProductionCycleOperatorReaderInterface {
    return new Interface(_abi) as IProductionCycleOperatorReaderInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IProductionCycleOperatorReader {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IProductionCycleOperatorReader;
  }
}
