/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "IERC1155Errors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1155Errors__factory>;
    getContractFactory(
      name: "IERC20Errors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Errors__factory>;
    getContractFactory(
      name: "IERC721Errors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Errors__factory>;
    getContractFactory(
      name: "IERC1363",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1363__factory>;
    getContractFactory(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20__factory>;
    getContractFactory(
      name: "IERC20Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Metadata__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "SafeERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SafeERC20__factory>;
    getContractFactory(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC165__factory>;
    getContractFactory(
      name: "ReentrancyGuard",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ReentrancyGuard__factory>;
    getContractFactory(
      name: "CollateralVault",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CollateralVault__factory>;
    getContractFactory(
      name: "IProductionCycleOperatorReader",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IProductionCycleOperatorReader__factory>;
    getContractFactory(
      name: "CycleMarketplace",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CycleMarketplace__factory>;
    getContractFactory(
      name: "IProductionCycle",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IProductionCycle__factory>;
    getContractFactory(
      name: "CycleShareToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CycleShareToken__factory>;
    getContractFactory(
      name: "CycleTokenMarketplace",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CycleTokenMarketplace__factory>;
    getContractFactory(
      name: "ICycleToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ICycleToken__factory>;
    getContractFactory(
      name: "CycleTokenMarketplaceV2",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CycleTokenMarketplaceV2__factory>;
    getContractFactory(
      name: "ICycleToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ICycleToken__factory>;
    getContractFactory(
      name: "FiatSettlement",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FiatSettlement__factory>;
    getContractFactory(
      name: "ILiquidityVaultLike",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ILiquidityVaultLike__factory>;
    getContractFactory(
      name: "IProductionCycleFunding",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IProductionCycleFunding__factory>;
    getContractFactory(
      name: "IUniswapV2FactoryLike",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IUniswapV2FactoryLike__factory>;
    getContractFactory(
      name: "IUniswapV2RouterLike",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IUniswapV2RouterLike__factory>;
    getContractFactory(
      name: "LiquidityManager",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LiquidityManager__factory>;
    getContractFactory(
      name: "LiquidityVault",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LiquidityVault__factory>;
    getContractFactory(
      name: "MockCycleFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockCycleFactory__factory>;
    getContractFactory(
      name: "MockDexFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockDexFactory__factory>;
    getContractFactory(
      name: "MockDexRouter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockDexRouter__factory>;
    getContractFactory(
      name: "MockUSDC",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockUSDC__factory>;
    getContractFactory(
      name: "MockUSDCFaucet",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockUSDCFaucet__factory>;
    getContractFactory(
      name: "OperatorRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.OperatorRegistry__factory>;
    getContractFactory(
      name: "IProductionCycle",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IProductionCycle__factory>;
    getContractFactory(
      name: "PortfolioVault",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PortfolioVault__factory>;
    getContractFactory(
      name: "ICollateralVault",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ICollateralVault__factory>;
    getContractFactory(
      name: "ILiquidityManager",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ILiquidityManager__factory>;
    getContractFactory(
      name: "IVerifierRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IVerifierRegistry__factory>;
    getContractFactory(
      name: "ProductionCycle",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ProductionCycle__factory>;
    getContractFactory(
      name: "ICollateralVault2",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ICollateralVault2__factory>;
    getContractFactory(
      name: "ILiquidityManagerFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ILiquidityManagerFactory__factory>;
    getContractFactory(
      name: "ILiquidityVaultDepositor",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ILiquidityVaultDepositor__factory>;
    getContractFactory(
      name: "ProductionCycleFactoryV2",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ProductionCycleFactoryV2__factory>;
    getContractFactory(
      name: "ProtocolTreasury",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ProtocolTreasury__factory>;
    getContractFactory(
      name: "IReserveCompensatedCycle",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IReserveCompensatedCycle__factory>;
    getContractFactory(
      name: "ReservePool",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ReservePool__factory>;
    getContractFactory(
      name: "ICycleFactoryReader",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ICycleFactoryReader__factory>;
    getContractFactory(
      name: "ICycleStateReader",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ICycleStateReader__factory>;
    getContractFactory(
      name: "VerifierRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.VerifierRegistry__factory>;
    getContractFactory(
      name: "YieldOracle",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.YieldOracle__factory>;

    getContractAt(
      name: "Ownable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "IERC1155Errors",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1155Errors>;
    getContractAt(
      name: "IERC20Errors",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Errors>;
    getContractAt(
      name: "IERC721Errors",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721Errors>;
    getContractAt(
      name: "IERC1363",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1363>;
    getContractAt(
      name: "ERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20>;
    getContractAt(
      name: "IERC20Metadata",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Metadata>;
    getContractAt(
      name: "IERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "SafeERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SafeERC20>;
    getContractAt(
      name: "IERC165",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC165>;
    getContractAt(
      name: "ReentrancyGuard",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ReentrancyGuard>;
    getContractAt(
      name: "CollateralVault",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.CollateralVault>;
    getContractAt(
      name: "IProductionCycleOperatorReader",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IProductionCycleOperatorReader>;
    getContractAt(
      name: "CycleMarketplace",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.CycleMarketplace>;
    getContractAt(
      name: "IProductionCycle",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IProductionCycle>;
    getContractAt(
      name: "CycleShareToken",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.CycleShareToken>;
    getContractAt(
      name: "CycleTokenMarketplace",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.CycleTokenMarketplace>;
    getContractAt(
      name: "ICycleToken",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ICycleToken>;
    getContractAt(
      name: "CycleTokenMarketplaceV2",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.CycleTokenMarketplaceV2>;
    getContractAt(
      name: "ICycleToken",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ICycleToken>;
    getContractAt(
      name: "FiatSettlement",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.FiatSettlement>;
    getContractAt(
      name: "ILiquidityVaultLike",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ILiquidityVaultLike>;
    getContractAt(
      name: "IProductionCycleFunding",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IProductionCycleFunding>;
    getContractAt(
      name: "IUniswapV2FactoryLike",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IUniswapV2FactoryLike>;
    getContractAt(
      name: "IUniswapV2RouterLike",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IUniswapV2RouterLike>;
    getContractAt(
      name: "LiquidityManager",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.LiquidityManager>;
    getContractAt(
      name: "LiquidityVault",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.LiquidityVault>;
    getContractAt(
      name: "MockCycleFactory",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockCycleFactory>;
    getContractAt(
      name: "MockDexFactory",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockDexFactory>;
    getContractAt(
      name: "MockDexRouter",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockDexRouter>;
    getContractAt(
      name: "MockUSDC",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockUSDC>;
    getContractAt(
      name: "MockUSDCFaucet",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockUSDCFaucet>;
    getContractAt(
      name: "OperatorRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.OperatorRegistry>;
    getContractAt(
      name: "IProductionCycle",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IProductionCycle>;
    getContractAt(
      name: "PortfolioVault",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PortfolioVault>;
    getContractAt(
      name: "ICollateralVault",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ICollateralVault>;
    getContractAt(
      name: "ILiquidityManager",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ILiquidityManager>;
    getContractAt(
      name: "IVerifierRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IVerifierRegistry>;
    getContractAt(
      name: "ProductionCycle",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ProductionCycle>;
    getContractAt(
      name: "ICollateralVault2",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ICollateralVault2>;
    getContractAt(
      name: "ILiquidityManagerFactory",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ILiquidityManagerFactory>;
    getContractAt(
      name: "ILiquidityVaultDepositor",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ILiquidityVaultDepositor>;
    getContractAt(
      name: "ProductionCycleFactoryV2",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ProductionCycleFactoryV2>;
    getContractAt(
      name: "ProtocolTreasury",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ProtocolTreasury>;
    getContractAt(
      name: "IReserveCompensatedCycle",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IReserveCompensatedCycle>;
    getContractAt(
      name: "ReservePool",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ReservePool>;
    getContractAt(
      name: "ICycleFactoryReader",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ICycleFactoryReader>;
    getContractAt(
      name: "ICycleStateReader",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ICycleStateReader>;
    getContractAt(
      name: "VerifierRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.VerifierRegistry>;
    getContractAt(
      name: "YieldOracle",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.YieldOracle>;

    deployContract(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "IERC1155Errors",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1155Errors>;
    deployContract(
      name: "IERC20Errors",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Errors>;
    deployContract(
      name: "IERC721Errors",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Errors>;
    deployContract(
      name: "IERC1363",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1363>;
    deployContract(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC20>;
    deployContract(
      name: "IERC20Metadata",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Metadata>;
    deployContract(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "SafeERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SafeERC20>;
    deployContract(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC165>;
    deployContract(
      name: "ReentrancyGuard",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ReentrancyGuard>;
    deployContract(
      name: "CollateralVault",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.CollateralVault>;
    deployContract(
      name: "IProductionCycleOperatorReader",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IProductionCycleOperatorReader>;
    deployContract(
      name: "CycleMarketplace",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.CycleMarketplace>;
    deployContract(
      name: "IProductionCycle",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IProductionCycle>;
    deployContract(
      name: "CycleShareToken",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.CycleShareToken>;
    deployContract(
      name: "CycleTokenMarketplace",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.CycleTokenMarketplace>;
    deployContract(
      name: "ICycleToken",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ICycleToken>;
    deployContract(
      name: "CycleTokenMarketplaceV2",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.CycleTokenMarketplaceV2>;
    deployContract(
      name: "ICycleToken",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ICycleToken>;
    deployContract(
      name: "FiatSettlement",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FiatSettlement>;
    deployContract(
      name: "ILiquidityVaultLike",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ILiquidityVaultLike>;
    deployContract(
      name: "IProductionCycleFunding",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IProductionCycleFunding>;
    deployContract(
      name: "IUniswapV2FactoryLike",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IUniswapV2FactoryLike>;
    deployContract(
      name: "IUniswapV2RouterLike",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IUniswapV2RouterLike>;
    deployContract(
      name: "LiquidityManager",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LiquidityManager>;
    deployContract(
      name: "LiquidityVault",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LiquidityVault>;
    deployContract(
      name: "MockCycleFactory",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockCycleFactory>;
    deployContract(
      name: "MockDexFactory",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockDexFactory>;
    deployContract(
      name: "MockDexRouter",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockDexRouter>;
    deployContract(
      name: "MockUSDC",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockUSDC>;
    deployContract(
      name: "MockUSDCFaucet",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockUSDCFaucet>;
    deployContract(
      name: "OperatorRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.OperatorRegistry>;
    deployContract(
      name: "IProductionCycle",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IProductionCycle>;
    deployContract(
      name: "PortfolioVault",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PortfolioVault>;
    deployContract(
      name: "ICollateralVault",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ICollateralVault>;
    deployContract(
      name: "ILiquidityManager",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ILiquidityManager>;
    deployContract(
      name: "IVerifierRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IVerifierRegistry>;
    deployContract(
      name: "ProductionCycle",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ProductionCycle>;
    deployContract(
      name: "ICollateralVault2",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ICollateralVault2>;
    deployContract(
      name: "ILiquidityManagerFactory",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ILiquidityManagerFactory>;
    deployContract(
      name: "ILiquidityVaultDepositor",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ILiquidityVaultDepositor>;
    deployContract(
      name: "ProductionCycleFactoryV2",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ProductionCycleFactoryV2>;
    deployContract(
      name: "ProtocolTreasury",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ProtocolTreasury>;
    deployContract(
      name: "IReserveCompensatedCycle",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IReserveCompensatedCycle>;
    deployContract(
      name: "ReservePool",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ReservePool>;
    deployContract(
      name: "ICycleFactoryReader",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ICycleFactoryReader>;
    deployContract(
      name: "ICycleStateReader",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ICycleStateReader>;
    deployContract(
      name: "VerifierRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.VerifierRegistry>;
    deployContract(
      name: "YieldOracle",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.YieldOracle>;

    deployContract(
      name: "Ownable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "IERC1155Errors",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1155Errors>;
    deployContract(
      name: "IERC20Errors",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Errors>;
    deployContract(
      name: "IERC721Errors",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Errors>;
    deployContract(
      name: "IERC1363",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1363>;
    deployContract(
      name: "ERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC20>;
    deployContract(
      name: "IERC20Metadata",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Metadata>;
    deployContract(
      name: "IERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "SafeERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SafeERC20>;
    deployContract(
      name: "IERC165",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC165>;
    deployContract(
      name: "ReentrancyGuard",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ReentrancyGuard>;
    deployContract(
      name: "CollateralVault",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.CollateralVault>;
    deployContract(
      name: "IProductionCycleOperatorReader",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IProductionCycleOperatorReader>;
    deployContract(
      name: "CycleMarketplace",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.CycleMarketplace>;
    deployContract(
      name: "IProductionCycle",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IProductionCycle>;
    deployContract(
      name: "CycleShareToken",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.CycleShareToken>;
    deployContract(
      name: "CycleTokenMarketplace",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.CycleTokenMarketplace>;
    deployContract(
      name: "ICycleToken",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ICycleToken>;
    deployContract(
      name: "CycleTokenMarketplaceV2",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.CycleTokenMarketplaceV2>;
    deployContract(
      name: "ICycleToken",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ICycleToken>;
    deployContract(
      name: "FiatSettlement",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FiatSettlement>;
    deployContract(
      name: "ILiquidityVaultLike",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ILiquidityVaultLike>;
    deployContract(
      name: "IProductionCycleFunding",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IProductionCycleFunding>;
    deployContract(
      name: "IUniswapV2FactoryLike",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IUniswapV2FactoryLike>;
    deployContract(
      name: "IUniswapV2RouterLike",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IUniswapV2RouterLike>;
    deployContract(
      name: "LiquidityManager",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LiquidityManager>;
    deployContract(
      name: "LiquidityVault",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LiquidityVault>;
    deployContract(
      name: "MockCycleFactory",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockCycleFactory>;
    deployContract(
      name: "MockDexFactory",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockDexFactory>;
    deployContract(
      name: "MockDexRouter",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockDexRouter>;
    deployContract(
      name: "MockUSDC",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockUSDC>;
    deployContract(
      name: "MockUSDCFaucet",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockUSDCFaucet>;
    deployContract(
      name: "OperatorRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.OperatorRegistry>;
    deployContract(
      name: "IProductionCycle",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IProductionCycle>;
    deployContract(
      name: "PortfolioVault",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PortfolioVault>;
    deployContract(
      name: "ICollateralVault",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ICollateralVault>;
    deployContract(
      name: "ILiquidityManager",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ILiquidityManager>;
    deployContract(
      name: "IVerifierRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IVerifierRegistry>;
    deployContract(
      name: "ProductionCycle",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ProductionCycle>;
    deployContract(
      name: "ICollateralVault2",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ICollateralVault2>;
    deployContract(
      name: "ILiquidityManagerFactory",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ILiquidityManagerFactory>;
    deployContract(
      name: "ILiquidityVaultDepositor",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ILiquidityVaultDepositor>;
    deployContract(
      name: "ProductionCycleFactoryV2",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ProductionCycleFactoryV2>;
    deployContract(
      name: "ProtocolTreasury",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ProtocolTreasury>;
    deployContract(
      name: "IReserveCompensatedCycle",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IReserveCompensatedCycle>;
    deployContract(
      name: "ReservePool",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ReservePool>;
    deployContract(
      name: "ICycleFactoryReader",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ICycleFactoryReader>;
    deployContract(
      name: "ICycleStateReader",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ICycleStateReader>;
    deployContract(
      name: "VerifierRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.VerifierRegistry>;
    deployContract(
      name: "YieldOracle",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.YieldOracle>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
