/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ICollateralVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "collateralBalance"
      | "releaseCollateral"
      | "slashCollateral"
      | "slashToRecipient"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "collateralBalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "releaseCollateral",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "slashCollateral",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "slashToRecipient",
    values: [AddressLike, BigNumberish, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "collateralBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "releaseCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "slashCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "slashToRecipient",
    data: BytesLike
  ): Result;
}

export interface ICollateralVault extends BaseContract {
  connect(runner?: ContractRunner | null): ICollateralVault;
  waitForDeployment(): Promise<this>;

  interface: ICollateralVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  collateralBalance: TypedContractMethod<
    [operator: AddressLike],
    [bigint],
    "view"
  >;

  releaseCollateral: TypedContractMethod<
    [operator: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  slashCollateral: TypedContractMethod<
    [operator: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  slashToRecipient: TypedContractMethod<
    [operator: AddressLike, amount: BigNumberish, recipient: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "collateralBalance"
  ): TypedContractMethod<[operator: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "releaseCollateral"
  ): TypedContractMethod<
    [operator: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "slashCollateral"
  ): TypedContractMethod<
    [operator: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "slashToRecipient"
  ): TypedContractMethod<
    [operator: AddressLike, amount: BigNumberish, recipient: AddressLike],
    [void],
    "nonpayable"
  >;

  filters: {};
}
